Pizzeria/Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

Pizzeria/pizzas/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza, name='pizza'),
    path('new_comment/<int:pizza_id>/',views.new_comment, name='new_comment'),
    path('picture', views.pizza, name = 'picture'),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Pizzeria/pizzas/models.py
from django.db import models

# Create your models here.

#Define a model Pizza with a field called pizza_name 
#This field is the name of the pizza such as Hawaiian, etc.
#Define a model called Topping with fields called pizza and 
# topping_name. The pizza field should be a foreign key to 
# the Pizza model, and topping_name should include sausage, etc.

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    #picture = models.ImageField(upload_to='images/')
    
    def __str__(self):
        return self.pizza_name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField()

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)

    def __str__(self):
        return self.comment

Pizzeria/pizzas/forms.py
from django import forms

from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {'comment': 'Comment'}
        widgets = {'comment': forms.Textarea(attrs={'cols':80})}

Pizzeria/pizzas/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')


def pizzas(request):
    pizzas = Pizza.objects.all()

    context = {'all_pizzas':pizzas}

    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    p = Pizza.objects.get(id=pizza_id)
    toppings = Topping.objects.filter(pizza=p)
    
    context = {'pizza':p, 'toppings':toppings}

    return render(request, 'pizzas/pizza.html', context)

def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
    context = {'form':form, 'pizza':pizza} 
    return render(request, 'pizzas/new_comment.html', context)

Pizzeria/pizzas/templates/pizzas/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>
            <a href="{% url 'pizzas:index' %}" >Pizzeria </a>
        </title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>


    <body>

        <!-- Static navbar -->

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'pizzas:index' %}">
                    Pizzeria</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'pizzas:pizzas' %}" >Pizza Options </a></li>
                </ul>

            
            </div><!--/.nav-collapse -->

        </div>
    </nav>
        <div class="container">

            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        
        </div> <!-- /container -->
        
    </body>
</html>

Pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Luke's Pizzeria </p>

<p> Order pizza from the Luke's Pizzeria! </p>


{% endblock content %}

Pizzeria/pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %} 


{% block content %} 
<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method="post">

    {% csrf_token %} 

    {{form.as_p}} 

    <button name="submit">Add Comment</button>
</form>

{% endblock content %} 

Pizzeria/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizza: {{ pizza }} </p>
<!--
<div>
   -- <img src="{{ pizza.picture.url }}" width=400 height=auto/>
--</div>
-->
<p> Toppings: </p>

<ul>
    {% for t in toppings %}

    <li> {{ t.topping_name }} </li>

    {% empty %}
    <li> No toppings have been added yet.</li>
    {% endfor %}
    
</ul>

<p>
    Comments: 
</p>
<li>
    <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a comment</a>
</li>
    {% for c in comment %} 
    <li> {{ c }} </li>
    {% endfor %} 

{% endblock content %}

Pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizzas </p>

<ul>
    {% for pizza in all_pizzas %}

    <li> 
        <a href="{% url 'pizzas:pizza' pizza.id %}"> {{ pizza }}</a>
    </li>

    {% empty %}
    <li> No pizzas have been added yet.</li>
    {% endfor %}

</ul>

{% endblock content %}